{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "py-app-helm-chart.fullname" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "py-app-helm-chart.fullname" . }}
  minReplicas: {{ .Values.hpa.min_replicas }}
  maxReplicas: {{ .Values.hpa.max_replicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.target_cpu_utilization_percentage }}
{{- end }}
